<?php

namespace Idanieldrew\Rabbitmq\Queue;

use Idanieldrew\Rabbitmq\Queue\Jobs\RabbitmqJob;
use Idanieldrew\Rabbitmq\RabbitmqFacade;
use Illuminate\Contracts\Queue\Queue as Contract;
use Illuminate\Queue\Queue;
use Illuminate\Support\Facades\Log;
use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;

class RabbitmqQueue extends Queue implements Contract
{
    public $channel;

    public function __construct(protected AMQPStreamConnection $connection, protected array $config)
    {
        $this->channel = $this->connection->channel();
    }

    public function size($queue = null)
    {
        Log::alert('size');
    }

    public function push($job, $data = '', $queue = null)
    {
        Log::alert('push');

        return $this->enqueueUsing(
            $job,
            $this->createPayload($job, "hello", $data),
            $queue,
            null,
            function ($payload, $queue) {
                return $this->pushRaw($payload, "hello");
            }
        );
    }

    public function pushRaw($payload, $queue = null, array $options = [])
    {
        Log::alert('pushRaw');

        $message = new AMQPMessage($payload, [
            'Content-Type' => 'application/json',
            'delivery_mode' => 2,
        ]);

        $this->channel->queue_declare(
            $queue,
            false,
            false,
            false,
            false
        );

        $this->channel->basic_publish($message, '', $queue);
        return true;
    }

    public function later($delay, $job, $data = '', $queue = null)
    {
        Log::alert('later');

        return $this->pushRaw($data, $queue, [$delay]);
    }

    public function pop($queue = null)
    {
        Log::alert('pop');

        $this->channel->queue_declare(
            'hello',
            false,
            false,
            false,
            false
        );

        $message = $this->channel->basic_get('hello');

        if ($message instanceof AMQPMessage) {
            return new RabbitmqJob($this->container, $this, $this->connection->channel(), 'queue', $message);
        }
        return null;
    }

    public function clear($queue)
    {
        Log::alert('clear');
    }

    public function bulk($jobs, $data = '', $queue = null)
    {
        parent::bulk($jobs, $data, $queue); // TODO: Change the autogenerated stub
    }

    private function declareQueue($name)
    {
        /* $this->connection->channel()->exchange_declare(
             $this->config['exchange'],
             $this->config['exchange_type'],
             $this->config['exchange_passive'],
             $this->config['exchange_durable'],
             $this->config['exchange_auto_delete'],
             $this->config['exchange_internal'],
             $this->config['exchange_nowait']
         );*/

        $this->connection->channel()->queue_declare(
            $this->config['exchange'],
            $this->config['passive'] ?? false,
            $this->config['durable'] ?? false,
            $this->config['exclusive'] ?? false,
            $this->config['nowait'] ?? false
        );
    }

    public function release($delay, $job, $data, $queue, $attempts = 0)
    {
       dd('4444444444');
    }
}
